# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
    -   id: markdownlint
        args: ["--fix"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb", "80000"]

-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    - id: isort
      types: [python]
      args: ["--profile", "black"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic, types-PyYAML, types-python-dateutil]

-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black

# -   repo: https://github.com/PyCQA/pydocstyle
#     rev: 6.1.1
#     hooks:
#     -   id: pydocstyle
#         types: [python]
#         files: "src/.*"
#         args: ["--convention", "google", "--add-ignore", "D301"]

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        types: [python]

-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3.9014
    hooks:
    -   id: style-files
        args: ["--style_pkg", "styler", "--style_fun", "tidyverse_style"]
        exclude: "renv/library/.*"
    -   id: parsable-R
    -   id: no-browser-statement

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.0
    hooks:
    -   id: nbqa-isort
        args: ["--profile=black"]
    -   id: nbqa-black
    -   id: nbqa-pyupgrade
    -   id: nbqa-mypy
        additional_dependencies: [pydantic, mypy, types-python-dateutil]
        types: [jupyter]
