# (PART) Misc {-}

# About {-}

## The website

The purpose of this website is to serve as a resource for using my notes and work for this course in the future.
Originally, I built it using ['distill'](https://rstudio.github.io/distill/) and deployed it as a simple static website on GitHub.
This worked well and was quick to build because the notebooks did not need to be re-run each time.
Though it is a very flexible platform, it had some limitations and I didn't like the styling of the notebooks in HTML.
I'm sure this could have been endlessly adjusted in CSS, but I realized firs that the ['bookdown'](https://pkgs.rstudio.com/bookdown/) format may be more appropriate for my needs.

I transformed this site into a 'bookdown' book after completing the course.
It took a bit of rearrangement, but I think the product is more logical and easier to use.
It has replaced the 'distill' website completely and is deployed on GitHub.

## About me

My name is Joshua Cook and I am (at the time of taking this course and writing this About page) a graduate student at Harvard Medical School.
My research is on cancer genetics and I have a specific love of Bayesian modelling.
You can peruse more of my projects and other work on my GitHub profile at [jhrcook](https://github.com/jhrcook) or my [website](https://joshuacook.netlify.app).
