---
title: "Chapter 17 Exercises - Reproducing the the 'serial dilution assay'"
date: "2021-12-10"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "#>", dpi = 300)

rfiles <- list.files(here::here("src"), full.names = TRUE, pattern = "R$")
for (rfile in rfiles) {
  source(rfile)
}
```

My goal here is to fit the serial dilution model model and perform basic inferential analysis as demonstrated in Chapter 17.
The original publication by Gelman *et al.* is also available[^1].

[^1]: Gelman A, Chew GL, Shnaidman M. Bayesian analysis of serial dilution assays. Biometrics. 2004 Jun;60(2):407-17. doi: 10.1111/j.0006-341X.2004.00185.x. PMID: 15180666. https://pubmed.ncbi.nlm.nih.gov/15180666/

## Setup

```{r setup-show, message=FALSE, warning=FALSE}
library(rstan)
library(tidybayes)
library(tidyverse)

options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

theme_set(theme_classic() + theme(panel.grid.major = element_line(), strip.background = element_blank()))
```

Data copied from the book Figure 19.3 on page 473.

```{r}
dilution_standards_data <- tibble::tribble(
  ~conc, ~dilution, ~y,
  0.64, 1, c(101.8, 121.4),
  0.32, 1 / 2, c(105.2, 114.1),
  0.16, 1 / 4, c(92.7, 93.3),
  0.08, 1 / 8, c(72.4, 61.1),
  0.04, 1 / 16, c(57.6, 50.0),
  0.02, 1 / 32, c(38.5, 35.1),
  0.01, 1 / 64, c(26.6, 25.0),
  0, 0, c(14.7, 14.2),
) %>%
  mutate(rep = purrr::map(conc, ~ c("a", "b"))) %>%
  unnest(c(y, rep))
head(dilution_standards_data)
```

```{r}
dilution_standards_data %>%
  ggplot(aes(x = conc, y = y, color = rep)) +
  geom_line(alpha = 0.5, linetype = 2) +
  geom_point(alpha = 0.8) +
  scale_x_continuous(expand = expansion(c(0, 0.02)), limits = c(0, NA)) +
  scale_y_continuous(expand = expansion(c(0, 0.02)), limits = c(0, NA)) +
  scale_color_brewer(type = "qual", palette = "Set1")
```

```{r}
model_data <- list(
  N = nrow(dilution_standards_data),
  A = 30,
  x = dilution_standards_data$conc,
  y = dilution_standards_data$y
)
stan_mdl_file <- here::here("models", "serial-dilution.stan")
dilution_mdl <- stan(stan_mdl_file, data = model_data, refresh = 0)
```

```{r}
print(dilution_mdl, pars = c("beta", "alpha", "sigma"))
```

```{r}
rstan::stan_trace(dilution_mdl, pars = c("beta", "alpha", "sigma"), alpha = 0.4)
```

```{r, message=FALSE, warning=FALSE}
for (p in c("beta", "alpha", "sigma")) {
  p <- rstan::stan_plot(dilution_mdl, pars = "beta", ci_level = 0.89, outer_level = 0.95)
  print(p)
  p <- rstan::stan_dens(dilution_mdl, pars = "beta", alpha = 0.4) +
    scale_x_continuous(expand = expansion(c(0, 0))) +
    scale_y_continuous(expand = expansion(c(0, 0.02)))
  print(p)
}
```

```{r}
dilution_mdl_ppc <- rstan::extract(dilution_mdl)$ypred %>%
  as.data.frame() %>%
  as_tibble() %>%
  mutate(iteration = row_number()) %>%
  pivot_longer(-iteration, names_to = "data_pt_idx", values_to = "draw") %>%
  mutate(data_pt_idx = as.integer(str_remove(data_pt_idx, "V"))) %>%
  left_join(dilution_standards_data %>% mutate(data_pt_idx = row_number()), by = "data_pt_idx")

head(dilution_mdl_ppc)
```

```{r}
iters <- sample(seq(min(dilution_mdl_ppc$iteration), max(dilution_mdl_ppc$iteration)), 100)
dilution_mdl_ppc %>%
  filter(iteration %in% iters) %>%
  mutate(grp = glue::glue("{iteration}-{rep}")) %>%
  ggplot(aes(x = conc, y = draw, group = grp)) +
  geom_line(alpha = 0.1) +
  geom_line(aes(x = conc, y = y, group = rep), data = dilution_standards_data, color = "blue") +
  geom_point(aes(x = conc, y = y), data = dilution_standards_data, color = "blue", inherit.aes = FALSE) +
  scale_x_continuous(expand = expansion(c(0, 0.02))) +
  scale_y_continuous(expand = expansion(c(0, 0.02)))
```


TODO: predictions on new data across more dilutions $x$
