---
title: "11. Normal approximation & Frequency properties"
date: "2021-11-19"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 300, comment = "#>")
```

## Resources

- reading:
  - BDA3 ch 4. *Asymptotics and connections to non-Bayesian approaches*
  - [reading instructions](../reading-instructions/BDA3_ch04_reading-instructions.pdf)
- lectures:
  - [Lecture 11.1. 'Normal approximation (Laplace approximation)'](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=e22fedc7-9fd3-4d1e-8318-ab1000ca45a4)
  - [Lecture 11.2. 'Large sample theory and counter examples'](https://aalto.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a8e38a95-a944-4f3d-bf95-ab1000dbdf73)
- [slides](../slides/slides_ch04.pdf)

## Notes

### Reading instructions

- chapter outline:
  - 4.1 Normal approximation (Laplace’s method)
  - 4.2 Large-sample theory
  - 4.3 Counter examples
  - 4.4 Frequency evaluation (not part of the course, but interesting)
  - 4.5 Other statistical methods (not part of the course, but interesting)

### Chapter 4. Asymptotics and connections to non-Bayesian approaches

- notes from the book

### Lecture notes

#### Lecture 11.1. 'Normal approximation (Laplace approximation)'



#### Lecture 11.2. 'Large sample theory and counter examples'
